name: python-statistics
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.20.*
  - scipy
  - pandas=1.3.*
  - matplotlib=3.4.*
  - xlrd
  - openpyxl
  - notebook
  - scikit-learn
  - statsmodels
